spring.application.name=parser
spring.datasource.url=jdbc:postgresql://185.247.17.9:5432/nikita_db
spring.datasource.username=user
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
